#!/usr/bin/env python3

"""
Send e-mail to multiple recipients via FI MUNI SMTP.

This scripts sends e-mail message to multiple recipients as separate e-mail
for each recipient with its own To: header.
 * E-mail format: html with headers (see example).
 * Recipients format: text file with each address at separate line.
E-mail is sent as multipart message with html and text version too. Text version
is generated via pandoc from html.
"""

import sys
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from getpass import getpass
import pypandoc
import re

if len(sys.argv) < 4:
    sys.stderr.write('Usage: mailer FI-MUNI-login recipients-filename body-filename\n')
    sys.exit(1)

with open(sys.argv[2], 'r') as f:
    recipients = f.read().splitlines()

msg = MIMEMultipart('alternative')
html_content = open(sys.argv[3], encoding='utf-8').read()

pos = html_content.find('\n\n')
headers = html_content[:pos]
html_content = html_content[pos+2:]
for header in headers.split('\n'):
    res = re.match(r'^(.*?): ?(.*)$', header)
    if res:
        key, value = res.group(1), res.group(2)
        msg[key] = value
        print('%s: %s' % (key, value))
    else:
        raise Exception('Invalid header: %s' % (header))
print('---')

txt_content = pypandoc.convert(html_content, 'markdown', format='html')

msg.attach(MIMEText(txt_content, 'plain', 'utf-8'))
msg.attach(MIMEText(html_content, 'html', 'utf-8'))

print('Connecting to relay.fi.muni.cz...', end='')
sys.stdout.flush()
try:
    s = smtplib.SMTP_SSL('relay.fi.muni.cz')
    print('OK')
except Exception as e:
    sys.stderr.write('\n'+str(e)+'\n')
    sys.exit(1)

print('Will send to %s recipients.' % (len(recipients)))
password = getpass('Enter password for %s@relay.fi.muni.cz: ' % (sys.argv[1]))
try:
    print('Authenticating...', end='')
    sys.stdout.flush()
    s.login(sys.argv[1], password)
    print('OK')
except Exception as e:
    sys.stderr.write('\n'+str(e)+'\n')
    sys.exit(1)

for recipient in recipients:
    print('Sending to '+recipient+'...', end='')
    sys.stdout.flush()
    del msg['To']
    msg['To'] = recipient
    try:
        s.sendmail(msg['Sender'], recipient, msg.as_string())
        print('OK')
    except Exception as e:
        sys.stderr.write(str(e)+'\n')
